# This script is used to setup NTLs Connection to 1 or multiple HSMs.
---
- hosts: all
  vars:
    MIN_CLIENT_DIR: $HOME//home/ec2-user/LunaClient-Minimal-10.7.2-16.x86_64
    HSM_IPS: 127.0.0.1, 127.0.0.2
  tasks:
# Pre-checks to ensure Luna Client would connect to HSMs servers

# 1. Check Lunacm and VTL configuration

# 2. Check conectivity to each HSM.

# 3. Check all server.pem for the HSMs and Client Certs are available

# Copy Certificates into LunaClient certs forlder

# Check or register LunaClient certs on HSMs.

# Test connectivity to HSMs
