# This script is used to setup NTLs Connection to 1 or multiple HSMs.
---
- hosts: all
  vars:
    MIN_CLIENT_DIR: $HOME/LunaClient-Minimal-10.7.2-16.x86_64
    hsm_ips:
      - 76.239.141.209
      - 76.239.141.216
    client_name: jv_boa
    partition_name: jv_boa
    hsm_user: jvaldes
    password: "Gemalto123!"
    partition_domain: "Thales123!"
    co_password: "Thales123"
  tasks:
    # Pre-checks to ensure Luna Client would connect to HSMs servers
    # NOTE: This script will launch lunacm and run ccfg per Minimal Luna client.

    # 1. Run lunacm with clientconfig to deploy the HSM and partition registration
    # ./bin/64/lunacm -q clientconfig deploy -server 76.239.141.209 -client jv_boa -partition jv1 -user jvaldes -password "Gemalto123!" -v

    - name: Run Lunacm for Partition registration
      command: ./bin/64/lunacm -q clientconfig deploy -server {{ item }} -client {{ client_name }} -partition {{ partition_name }} -user {{ hsm_user }} -password {{ password }} -v
      args:
        chdir: "{{ MIN_CLIENT_DIR }}"
      loop: "{{ hsm_ips}}"
      register: lunacm_deploy_result
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Display command result
      debug:
        msg: "{{ lunacm_deploy_result.stdout }}"
# 2. Create the HA cluster on each client.
